### ISSUE TITLE
Packaging: PHP extension intl is now required

### ISSUE THREAD

**Issue by Seb35** [Icinga/ipl-i18n#11]
When upgrading today from Icingaweb2 2.8.2 to 2.9.1 (on Ubuntu), I got:
```
PHP message: PHP Fatal error:  Uncaught Error: Class 'Locale' not found in /usr/share/icinga-php/ipl/vendor/ipl/i18n/src/Locale.php:122
```

It appears the PHP extension intl is now required since [this commit](https://github.com/Icinga/ipl-i18n/commit/751c8562b124834f0055ffa9639e39ab2ca9bd38). It should be added in composer.json and in the Debian package distributed on packages.icinga.com.

In the meantime, `sudo apt install php-intl` solves the issue.

**Comment by nilmerg** [comment]
Thanks for the heads up! We didn't require this as [PHP's documentation says it's bundled](https://www.php.net/manual/en/extensions.membership.php#extensions.membership.bundled).

Doesn't seem so on your OS though. Which Ubuntu is this exactly?

**Comment by Seb35** [comment]
It is Ubuntu 20.04.2 LTS and PHP 7.4.3-4ubuntu2.5.

The [documentation on the intl extension](https://www.php.net/manual/en/intl.requirements.php) says it “is bundled with PHP as of PHP version 5.3.0”.

But looking on packages.ubuntu.com, when PHP is installed (package [php7.4](https://packages.ubuntu.com/focal/php7.4)), only the PHP extensions php7.4-opcache and php7.4-json are installed, through the SAPI (libapache2-mod-php7.4, php7.4-fpm, or php7.4-cgi).

I guess the word “bundled” on [PHP documentation](https://www.php.net/manual/en/extensions.membership.php#extensions.membership.bundled) means the source code of the extension is included in main PHP source code, but not necessarily it is always distributed with PHP on binary packages.

**Comment by Seb35** [comment]
As expected, the dependencies is identical on Debian Buster, see package [php7.3](https://packages.debian.org/buster/php7.3).

To be sure about package dependencies, I created a new VM with Ubuntu 20.04, installed php7.4: the package php7.4-intl is not installed. (I see php7.4-readline is installed also as a dependency of php7.4-cli.)
