### ISSUE TITLE
Install instructions don’t work

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/ipl-i18n#2]
Even w/ https://github.com/Al2Klimov/ipl-validator/commit/5f1b976b0c2117d5293d91768c329d526ce196c7 `composer require ipl/i18n` says: Could not find a matching version of package ipl/i18n.

**Comment by nilmerg** [comment]
There's no released version yet, hence none on [Packagist](https://packagist.org/?query=ipl%2F) yet.

**Comment by Al2Klimov** [comment]
So the current install instructions shall not exist, right?

**Comment by nilmerg** [comment]
There's none yet, because it's not used by anything. It will be part of https://github.com/Icinga/ipl eventually.

**Comment by Al2Klimov** [comment]
I’m going to use it in new validators.

**Comment by nilmerg** [comment]
Why? Just use `t()` and `tp()` and you're fine without it.

**Comment by Al2Klimov** [comment]
t? Inside a class in https://github.com/Icinga/ipl-validator ?

**Comment by nilmerg** [comment]
Yes.

**Comment by lippserd** [comment]
But tThis function is not defined, right? I would publish the package and then we could use it.

**Comment by nilmerg** [comment]
I wonder where the code is currently being used. Icinga DB Web right? An icingaweb2 module? Anyone?

I don't see a point in creating a release of this in a hush hush way. There's literally no-one/nothing forcing this right now. ipl-web also does use the functions without a dependency to this lib. Works fine.

**Comment by Al2Klimov** [comment]
And a composer-dev release?

**Comment by nilmerg** [comment]
Can we please stop and settle on the functions? There is no composer-dev using this.

**Comment by Al2Klimov** [comment]
Look: every IW2 **class** uses translate, right? IMAO the ipl stuff should unify it this way as well.

**Comment by nilmerg** [comment]
Yep, we unify things, that's why we use `t()` and `tp()` in every ipl library and Icinga DB Web. No need to complicate things.

**Comment by Al2Klimov** [comment]
And what’s the Translation trait for?

**Comment by lippserd** [comment]
`t()` is not defined in `ipl-validator` and I would discourage usage of this function when we've switched to `ipl-i18n`. `t()` is just there since we did not have traits back then. Having a package on packagist does not mean that we have to have a release. We have to state `dev-master` though in the meantime.

**Comment by nilmerg** [comment]
Okay, sure, do what you want. I don't care.

**Comment by Al2Klimov** [comment]
No! I do what **you** want: https://github.com/Icinga/icingadb-web/pull/156#issuecomment-818715450 Too bad you didn’t allow the Zend validators. Now _someone_ has to fix this issue. 😁
